# Raster-vector interactions {#raster-vector}

## Prerequisites {-}

- This chapter requires the following packages:

```{r, include=FALSE}
library(sf)
library(raster)
library(spData)
library(spDataLarge)
```

## Introduction

<!-- intro -->

## Cropping

<!-- replace with spDataLarge::elevation in the future -->

```{r}
srtm = raster((system.file("raster/srtm.tif", package = "spDataLarge")))
```

```{r}
zion = st_read((system.file("vector/zion.gpkg", package = "spDataLarge"))) %>% 
  st_transform(4326)
```

```{r}
srtm_cropped = crop(srtm, as(zion, "Spatial"))
```

```{r}
srtm_masked = mask(srtm_cropped, zion)
```

```{r cropmask, echo = FALSE}
library(tmap)
pz1 = tm_shape(srtm) + 
  tm_raster() + 
  tm_shape(zion) +
  tm_borders(lwd = 2)

pz2 = tm_shape(srtm_cropped) + 
  tm_raster() + 
  tm_shape(zion) +
  tm_borders(lwd = 2)

pz3 = tm_shape(srtm_masked) + 
  tm_raster() + 
  tm_shape(zion) +
  tm_borders(lwd = 2)

grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 2, heights = unit(c(0.5, 5), "null"))))

grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 3, heights = unit(c(0.25, 5), "null"))))
grid.text("Original", vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
grid.text("Cropped", vp = viewport(layout.pos.row = 1, layout.pos.col = 2))
grid.text("Masked", vp = viewport(layout.pos.row = 1, layout.pos.col = 3))
print(pz1, vp=viewport(layout.pos.col = 1))
print(pz2, vp=viewport(layout.pos.col = 2))
print(pz3, vp=viewport(layout.pos.col = 3))
```

## Extraction

<!-- extract -->
<!-- zonal stats -->

## Spatial interpolation ??
<!-- http://mdsumner.github.io/guerrilla/articles/irreg2.html -->

## Rasterization ??

## Vectorization ??
<!-- distances? -->

## Exercises
