---
output: html_document
editor_options: 
  chunk_output_type: inline
---
# Advanced map making

## Prerequisites {-}

- ...

```{r, include=FALSE}
pkgs_c11 = c(
        "cowplot",
        "wbstats",
        "rnaturalearth",
        "viridis",
        "sf",
        "tidyverse",
        "tmap",
        "units"
)
pacman::p_load(char = pkgs_c11)
if(!exists("world")) {
        source("code/01-introduction.R")
}
        
```

# Advanced map making {#adv-map}

<!-- 
- tmap
- ggplot2/ggmap (geom_sf, coord_sf)
- leaflet/mapview
- rasterVis ?
- shiny ?
- animations
- inset maps
- color palettes (viridis, etc.)
-->

## Animations

```{r ani_data_prep}
options(scipen = 999)

wb_data_create = function(indicator, our_name, year, ...){
        df = wb(indicator = indicator, startdate = year, enddate = year, ...) %>%
                as_data_frame() %>%
                select(iso_a2=iso2c, value) %>%
                mutate(indicator = our_name) %>%
                spread(indicator, value)
        return(df)
}

data_lifeExp = seq(1963, 2013, by=5) %>%
        set_names(.) %>%
        map_df(~wb_data_create(.x, indicator = "SP.DYN.LE00.IN",
                               our_name = "lifeExp",
                               country = "countries_only"), .id='year') %>%
        spread(year, lifeExp)

world_sf_temporal = ne_countries(returnclass = 'sf') %>%
        left_join(., data_lifeExp, by = c('iso_a2')) %>%
        mutate(area_km2 = set_units(st_area(.), km^2)) %>%
        select(iso_a2, name_long, continent, region_un, subregion, type, area_km2, `1963`:`2013`) %>%
        gather(year, lifeExp, `1963`:`2013`)
```

```{r animation1, eval=FALSE}
m1 = tm_shape(world_sf_temporal) + 
        tm_polygons("lifeExp") +
        tm_facets(by = "year", nrow = 1, ncol = 1, drop.units = TRUE)

animation_tmap(m1, filename = "figures/11-lifeExp_animation.gif", width = 2000, height = 600, delay = 40)
```

```{r animation2, eval=FALSE}
world_sf_temporal2 = filter(world_sf_temporal, !(continent %in% c("Seven seas (open ocean)", "Antarctica")))
m2 = tm_shape(world_sf_temporal2) +
        tm_polygons("lifeExp", n = 12) +
        tm_facets(by = "continent", along = "year", drop.units = TRUE, free.coords = TRUE)
m2
```


<!-- library(tmap) -->
<!-- library(rnaturalearth) -->
<!-- library(sf) -->
<!-- library(tidyverse) -->

<!-- df <- data_frame(name=c('Australia', 'Austria'), -->
<!--                  `1990`=c(16.8, 7.7), `1995`=c(17.9, 7.9), -->
<!--                  `2000`=c(18.9, 8.0), `2005`=c(20.1, 8.2), -->
<!--                  `2010`=c(22.2, 8.4), `2015`=c(23.9, 8.7)) -->

<!-- world_sf <- ne_countries(returnclass = 'sf') %>%  -->
<!--         select(name) %>%  -->
<!--         filter(name %in% c('Australia', 'Austria')) %>%  -->
<!--         left_join(., df, by = "name") %>%  -->
<!--         gather(year, pop_mln, `1990`:`2015`) -->

<!-- ani_map <- tm_shape(world_sf) +  -->
<!--         tm_polygons("pop_mln", n=12) + -->
<!--         tm_facets(by='name', along = "year", drop.units = TRUE, free.coords = TRUE) -->

<!-- animation_tmap(ani_map, filename="ani_map.gif", width=800) -->


<!-- p = ggplot(world_sf_temporal, aes(fill = lifeExp, frame = year)) + -->
<!--         geom_sf() + -->
<!--         scale_fill_viridis(name='Life \nexpectancy:') + -->
<!--         scale_y_continuous(expand = c(0,0)) + -->
<!--         scale_x_continuous(expand = c(0,0)) + -->
<!--         theme_void() + -->
<!--         # theme(legend.position = c(.15, .4)) + -->
<!--         coord_sf() -->

<!-- gganimate(p, filename = 'plot1.gif') -->

<!-- world_sf_temporal2 = filter(world_sf_temporal, !(continent %in% c("Seven seas (open ocean)", "Antarctica"))) -->
<!-- p2 = ggplot(world_sf_temporal2, aes(fill = lifeExp, frame = year)) + -->
<!--         geom_sf() + -->
<!--         scale_fill_viridis(name='Life \nexpectancy:') + -->
<!--         scale_y_continuous(expand = c(0,0)) + -->
<!--         scale_x_continuous(expand = c(0,0)) + -->
<!--         theme_void() + -->
<!--         facet_wrap(~continent, scales='free') + -->
<!--         coord_sf() -->

<!-- gganimate(p2, filename = 'plot2.gif') -->

<!-- world_sf_temporal3 = filter(world_sf_temporal, continent == 'Africa') -->
<!-- p3 = ggplot(world_sf_temporal3, aes(fill = lifeExp, frame = year)) + -->
<!--         geom_sf() + -->
<!--         scale_fill_viridis(name='Life \nexpectancy:', option = "B") + -->
<!--         scale_y_continuous(expand = c(0,0)) + -->
<!--         scale_x_continuous(expand = c(0,0)) + -->
<!--         theme_void() + -->
<!--         facet_wrap(~name_long, scales='free') + -->
<!--         coord_sf() -->

<!-- gganimate(p3, filename = 'plot3.gif') -->
