# Algorithms and functions for geocomputation

## Prerequisites {-}

In the introduction we promised to teach not how to use existing tools for Geocomputation in R, but also develop new ones, "in the form of shareable R scripts and functions".
This chapter aims to deliver on that promise.

We will consider example R scripts for geographic data and how to make them more reproducible in section \@ref(scripts).
Algorithms (or 'geoalgorithms' for geographic processes) are recipes for modifying inputs using a series of steps, resulting in an output, as described in section \@ref(geographic-algorithms).
To ease sharing and reproducibility algorithms can be placed into R function, which can then be distributed either in script files or as R packages, the building blocks of reproducible code.
That is the topic of section \@ref(functions).

It should be noted at the outset that none of these topics are specific to geographic data.
Although geoalgorithms do have a specific meaning originating in GIS software, most of the concepts apply in other domains.
For that reason instead of going into detail, our approach in this chapter is to provide illustrative examples and direct the reader to established resources, to avoid reinventing the wheel.


## Scripts

## Geographic algorithms

## Functions

## Case study

## Exercises
