```{r 10-ex-e0, message=FALSE}
library(sf)
library(terra)
```

<!-- qgisprocess 1-3 -->
<!-- sagagis 1 -->
<!-- sagagis supercells -->
<!-- expain/mention other segmentation techinques -->
<!-- mention supercells -- exercises?? -->
<!-- https://github.com/joaofgoncalves/SegOptim ?? -->
<!-- rgrass 1 -->
<!-- gdal 1-2 -->
1. Use `gdalinfo` via a system call for a raster\index{raster} file stored on disk of your choice.
What kind of information you can find there?

```{r}
link2GI::linkGDAL()
our_filepath = system.file("raster/elev.tif", package = "spData")
cmd = paste("gdalinfo", our_filepath)
system(cmd)
# Driver, file path, dimensions, CRS, resolution, bounding box, summary statistics
```

1. Use `gdalwarp` to decrease the resolution of your raster file (for example, if the resolution is 0.5, change it into 1). Note: `-tr` and `-r` flags will be used in this exercise.

```{r}
our_filepath = system.file("raster/elev.tif", package = "spData")
cmd2 = paste("gdalwarp", our_filepath, "new_elev.tif", "-tr 1 1", "-r bilinear")
system(cmd2)
```


<!-- postgis 1? -->
<!-- stac+gdalcubes 1 -->

<!-- 1. Create two overlapping polygons (`poly_1` and `poly_2`) with the help of the **sf**-package (see Chapter \@ref(spatial-class)).  -->

<!-- 1. Union `poly_1` and `poly_2` using `st_union()` and `qgis:union`. -->
<!-- What is the difference between the two union operations\index{vector!union}?  -->
<!-- How can we use the **sf**\index{sf} package to obtain the same result as QGIS\index{QGIS}? -->

<!-- 1. Calculate the intersection\index{vector!intersection} of `poly_1` and `poly_2` using: -->

<!--     - **RQGIS**, **RSAGA** and **rgrass** -->
<!--     - **sf** -->

<!-- 1. Attach `data(dem, package = "spDataLarge")` and `data(random_points, package = "spDataLarge")`. -->
<!-- Select randomly a point from `random_points` and find all `dem` pixels that can be seen from this point (hint: viewshed\index{viewshed}). -->
<!-- Visualize your result. -->
<!-- For example, plot a hillshade\index{hillshade}, and on top of it the digital elevation model\index{digital elevation model}, your viewshed\index{viewshed} output and the point. -->
<!-- Additionally, give `mapview` a try. -->

<!-- 1. Compute catchment area\index{catchment area} and catchment slope of `data("dem", package = "spDataLarge")` using **RSAGA** (see Section \@ref(saga)). -->



<!-- 1. Query all Californian highways from the PostgreSQL/PostGIS\index{PostGIS} database living in the QGIS\index{QGIS} Cloud introduced in this chapter (see Section \@ref(postgis)). -->


