# CLI/GUI integration

An important feature of R is it's command-line interface (CLI).
As mentioned in chapter \@ref(intro), doing GIS at the command-line makes it more reproducible, in-line with the principles of Geographic Data Science.
However, there are times when a graphical user interface (GUI) are useful.

This chapter outlines ways to facilitate integration between the approaches.
The 'CLI vs GUI' debate is often framed in adverserial terms but it does not have to be.
As outlined by Gary Sherman (who should be well-qualified to comment on the debate as he created the world's premier open source GUI-based GIS!), there are times when one can be better than the other:

> With the advent of 'modern' GIS software, most people want to point and
click their way through life. That’s good, but there is a tremendous amount
of flexibility and power waiting for you with the command line. Many times
you can do something on the command line in a fraction of the time you
can do it with a GUI.

But there are times when it's useful to 'point and click'.

<!-- Idea: bullet points of times when GUI-based systems (particularly QGIS) are advantageous. -->

This chapter will outline how you can use portable file formats, packages such as **RQGIS**, **RSAGA** and **rgrass7**, alongside good knowledge of the strengths and weaknesses of 'CLIs vs GUIs'.

<!-- Sound like a good list of contents? -->
