# Ecological example
Required knowledge: chapters 3, 4, chapter r-gis bridges, chapter spatial cross-validation

keywords: species distribution modeling, floristic modeling, spatial cross-validation, spatial autocorrelation, ordination (NMDS, Isomap), predictive mapping

structure:
1. intro ecological modeling and related applications beyond ecology
2. introduce research question, shortly the dataset and the planned approach
3. ordination
4. retrieving predictors and quick data exploration
5. model of the ordination scores
6. predictive mapping of floristic composition including spatial cross-validation
7. discussion: what could be done better or alternatives and again emphasizing that the methods shown
finally, point to books on ecological modeling especially emphasizing Alain Zuur's books

Fog oases are one of the most fascinating vegetation formations I have ever encountered. 
These formations, locally termed *lomas* develop on mountains along the coastal deserts of Peru and Chile.
The desertical remoteness and its extreme harsh conditions spawned a truly unique and endemic flora and fauna.
The annual rain input is less than 30-50 mm on average.
Still, plants survive this extreme aridity by combing out fog which develops below the temperature inversion caused by the cold Humboldt current in austral winter.
Every once in a while, El Ni{\~n}o brings torrential rainfalls to this sun-baked environment causing on the one hand the desert to bloom, and on the other hand giving tree seedlings the chance to develop roots long enough to survive the following aridity.
Unfortunately, fog oases are heavily endangered mostly by human activities (grazing and agriculture) but also by climate change.
To effectively protect the last remnants of this unique vegetation formation, we need to know its floristic composition and spatial distribution.
*Lomas* mountains also have an economical, i.e. touristical value.
The vast majority of Peruvian are living in the coastal desert, and seldomly have a chance to leave it.
Scientists long found out that green oases are of utmost importance for human well-being, especially for metropolitan dwellers such as the people from Lima.
The only green space in the immediate vicinity of Lima are *lomas* mountains.
This even increases the immense recreational value of such green oases, and the need to effectively protect them.