--- 
title: 'Geocomputation with R'
author:
- Robin Lovelace
- Jakub Nowosad
date: '`r Sys.Date()`'
knit: bookdown::render_book
site: bookdown::bookdown_site
documentclass: book
bibliography:
  - refs.bib
  - packages.bib
biblio-style: apalike
link-citations: yes
github-repo: Robinlovelace/geocompr
url: https\://Robinlovelace.github.io/geocompr/
---

```{r, echo=FALSE, include=FALSE}
# source("code/before_script.R")
```

# Prerequisites {-}

You should be able to reproduce all the examples on your computer with the following command:

```{r, eval=FALSE}
bookdown::render_book("index.Rmd")
```

The code below makes some checks to ensure that you have the necessary packages:

```{r, message=FALSE}
if(!require(devtools)) {
  install.packages("devtools")
}

if(!require(geocompr)) {
  devtools::install(pkg = ".", dependencies = TRUE)
}
# devtools::install_github("robinlovelace/geocompr")
```

For further details see the book's GitHub page at [Robinlovelace/geocompr](https://github.com/Robinlovelace/geocompr#geocomputation-with-r).
