## ---- message=FALSE, results='hide'--------------------------------------
library(sf)
library(tidyverse)
library(spDataLarge)
library(stplanr)      # a package for transport data
library(tmap)         # a visualization package

## ---- echo=FALSE, eval=FALSE---------------------------------------------
## # code that generated the input data - see also ?bristol_ways
## # source("code/08-transport-data-gen.R")
## # view input data
## summary(bristol_ways)
## summary(bristol_ttwa)
## summary(bristol_region)
## 
## region_all = rbind(bristol_region, bristol_ttwa)
## library(tmap)
## tmap_mode("view")
## qtm(bristol_ways, lines.col = "highway", lines.lwd = 3, lines.palette = c("green", "black", "red")) +
##   tm_scale_bar() +
##   tm_shape(region_all) +
##   tm_borders(lwd = c(5, 7), col = "darkblue")

## ----bristol, echo=FALSE, fig.cap="Bristol's transport network represented by colored lines for active (green), public (railways, black) and private motor (red) modes of travel. Blue border lines represent the inner city boundary and the larger Travel To Work Area (TTWA)."----
knitr::include_graphics("https://user-images.githubusercontent.com/1825120/34452756-985267de-ed3e-11e7-9f59-fda1f3852253.png")

## ---- eval=FALSE, echo=FALSE---------------------------------------------
## if(!require(readODS)) {
##   install.packages("readODS")
## }
## u = "https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/536823/local-area-walking-and-cycling-in-england-2015.zip"
## download.file(u, "local-area-walking-and-cycling-in-england-2015.zip")
## unzip("local-area-walking-and-cycling-in-england-2015.zip")
## View(readODS::read_ods("Table index.ods"))
## cw0103 = readODS::read_ods("cw0103.ods")
## View(cw0103)

## Another issue with small zones is related to anonymity rules.

## ------------------------------------------------------------------------
names(bristol_zones)

## ------------------------------------------------------------------------
nrow(bristol_od)
nrow(bristol_zones)

## ------------------------------------------------------------------------
zones_attr = bristol_od %>% 
  group_by(o) %>% 
  summarize_if(is.numeric, sum) %>% 
  rename(geo_code = o)

## ------------------------------------------------------------------------
summary(zones_attr$geo_code %in% bristol_zones$geo_code)

## ------------------------------------------------------------------------
zones_joined = left_join(bristol_zones, zones_attr, by = "geo_code")
sum(zones_joined$all)
names(zones_joined)

## ------------------------------------------------------------------------
zones_od = bristol_od %>% 
  group_by(d) %>% 
  summarize_if(is.numeric, sum) %>% 
  dplyr::select(geo_code = d, all_dest = all) %>% 
  inner_join(zones_joined, ., by = "geo_code")

## ---- eval=FALSE---------------------------------------------------------
## qtm(zones_od, c("all", "all_dest")) +
##   tm_layout(panel.labels = c("Origin", "Destination"))

## ----zones, echo=FALSE, fig.cap="Number of trips (commuters) living and working in the region. The left map shows zone of origin of commute trips; the right map shows zone of destination (generated by the script 12-zones.R).", message=FALSE----
source("code/12-zones.R", print.eval = TRUE)

## ------------------------------------------------------------------------
od_top5 = bristol_od %>% 
  arrange(desc(all)) %>% 
  top_n(5, wt = all)

## ----od, echo=FALSE------------------------------------------------------
od_top5 %>% 
  knitr::kable(caption = "Sample of the origin-destination data stored in the data frame object `bristol_od`. These represent the top 5 most common desire lines between zones in the study area.")

## ---- warning=FALSE------------------------------------------------------
od_intra = filter(bristol_od, o == d)
od_inter = filter(bristol_od, o != d)
desire_lines = od2line(od_inter, zones_od)

## ---- eval=FALSE---------------------------------------------------------
## qtm(desire_lines, lines.lwd = "all")

## ----desire, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Desire lines representing trip patterns in the Bristol Travel to Work Area. The four black lines represent the object the top 5 desire lines illustrated in Table 7.1."----
source("code/12-desire.R", print.eval = TRUE)

## ---- message=FALSE------------------------------------------------------
desire_lines$distance = as.numeric(st_length(desire_lines))
desire_carshort = dplyr::filter(desire_lines, car_driver > 300 & distance < 5000)

## ---- eval=FALSE---------------------------------------------------------
## route_carshort = line2route(desire_carshort, route_fun = route_osrm)

## ------------------------------------------------------------------------
desire_carshort$geom_car = st_geometry(route_carshort)

## ----routes, warning=FALSE, fig.cap="Routes along which many (300+) short (<5km Euclidean distance) car journeys are made (red) overlaying desire lines representing the same trips (black) and zone centroids (dots).", echo=FALSE, eval=FALSE----
## # commented-out as it adds little to the chapter (RL)
## plot(st_geometry(desire_carshort))
## plot(desire_carshort$geom_car, col = "red", add = TRUE)
## plot(st_geometry(st_centroid(zones_od)), add = TRUE)

## ------------------------------------------------------------------------
desire_rail = top_n(desire_lines, n = 3, wt = train)

## ------------------------------------------------------------------------
ncol(desire_rail)
desire_rail = line_via(desire_rail, bristol_stations)
ncol(desire_rail)

## ----stations, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Station nodes (red dots) used as intermediary points that convert straight desire lines with high rail usage (black) into three legs: to the origin station (red) via public transport (grey) and to the destination (a very short blue line)."----
zone_cents = st_centroid(zones_od)
zone_cents_rail = zone_cents[desire_rail, ]
plot(desire_rail$geometry, expandBB = c(.1, .1, .1, .1))
plot(desire_rail$leg_orig, add = TRUE, col = "red", lwd = 3)
plot(desire_rail$leg_via, add = TRUE, col = "grey", lwd = 2)
plot(bristol_stations, add = TRUE, col = "red")
plot(desire_rail$leg_dest, add = TRUE, col = "blue", lwd = 5)
plot(zone_cents_rail, add = TRUE, col = "black")
# library(tmap)
# tmap_mode("plot")
# qtm(bristol_stations, basemaps = "https://{s}.tile.thunderforest.com/transport/{z}/{x}/{y}.png?apikey=feae177da543411c9efa64160305212d", dots.col = "red", symbols.size = 2) +
#   tm_shape(desire_rail) +
#   tm_lines(col = "black", lwd = 4) +
#   tm_shape(legs) +
#   tm_lines()

## ------------------------------------------------------------------------
summary(bristol_ways)

## ------------------------------------------------------------------------
ways_freeway = bristol_ways %>% filter(maxspeed == "70 mph") 
ways_sln = SpatialLinesNetwork(ways_freeway)
slotNames(ways_sln)
weightfield(ways_sln)
class(ways_sln@g)

## ---- fig.cap="Illustration of a small route network, with segment thickness proportional to its betweeness, generated using the **igraph** package and described in the text."----
g = ways_sln@g
e = igraph::edge_betweenness(ways_sln@g)
plot(ways_sln@sl$geometry, lwd = e / 500)

## ---- eval=FALSE, echo=FALSE---------------------------------------------
## # not producing groups of routes so removing for now...
## m = igraph::clusters(g)
## igraph::V(g)$m = m$membership
## gdf = igraph::as_long_data_frame(g)

## ------------------------------------------------------------------------
path = sum_network_routes(ways_sln, 1, 20, "length")

## ---- eval=FALSE---------------------------------------------------------
## plot(st_geometry(path), col = "red", lwd = 10)
## plot(ways_sln@sl$geometry, add = TRUE)

## ---- eval=FALSE---------------------------------------------------------
## route_rail = desire_rail %>%
##   st_set_geometry("leg_orig") %>%
##   line2route(route_fun = route_osrm) %>%
##   st_set_crs(4326)

## ------------------------------------------------------------------------
route_cycleway = rbind(route_rail, route_carshort)
route_cycleway$all = c(desire_rail$all, desire_carshort$all)

## ---- eval=FALSE, echo=FALSE---------------------------------------------
## n_trips = route_cycleway$all / 100
## plot(route_cycleway["distance"], lwd = n_trips)

## ---- eval=FALSE---------------------------------------------------------
## qtm(route_cycleway, lines.lwd = "all")

## ----cycleways, echo=FALSE, message=FALSE, fig.cap="Potential routes along which to prioritise cycle infrastructure in Bristol, based on access key rail stations (red dots) and routes with many short car journeys (north of Bristol surrounding Stoke Bradley). Line thickness is proportional to number of trips."----
source("code/12-cycleways.R")
m_leaflet
# tmap_leaflet(m_leaflet) # not working
# online figure - backup
# u = "https://user-images.githubusercontent.com/1825120/39901156-a8ec9ef6-54be-11e8-94fb-0b5f6b48775e.png"

## ---- eval=FALSE, echo=FALSE---------------------------------------------
## sum(route_cycleway$distance)
## sum(st_length(route_cycleway))

## ---- echo=FALSE, eval=FALSE---------------------------------------------
## sum(route_cycleway$all) / sum(desire_lines$all) # around 2%
## d_intersect = desire_lines[route_cycleway, , op = st_crosses]
## sum(d_intersect$all) / sum(desire_lines$all) # around 2%

