library(sf)
p = st_sfc(st_point(c(0, 1)), st_point(c(1, 1)))
b = st_buffer(p, dist = 1)
i = st_intersection(b[1], b[2])
plot(b)
text(x = c(-0.5, 1.5), y = 1, labels = c("Geography", "R"))
plot(i, col = "lightgrey", add = TRUE)
