---
title: "Geocomputation with R - map of the U.S.A."
author: "Robin Lovelace, Jakub Nowosad, Jannes Muenchow"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

## Prerequisites {-}

The example below assue the following packages are loaded:

```{r packages, message=FALSE, warning=FALSE}
library(sf)
library(spData)
library(tidyverse)
library(tmap)
library(grid)
```

## Data preparation

```{r}
us_states2163 = st_transform(us_states, 2163)
```

## Ratio calculation

```{r}
us_states_area = st_area(st_as_sfc(st_bbox(us_states2163)))
hawaii_area = st_area(st_as_sfc(st_bbox(hawaii)))
alaska_area = st_area(st_as_sfc(st_bbox(alaska)))
``` 

```{r}
us_states_hawaii_ratio = as.numeric(hawaii_area/us_states_area)
us_states_alaska_ratio = as.numeric(alaska_area/us_states_area)
```

## Single maps creation

```{r}
us_states_map = tm_shape(us_states2163) +
  tm_polygons() + 
  tm_layout(frame = FALSE)
```

```{r}
hawaii_map = tm_shape(hawaii) +
  tm_polygons() + 
  tm_layout(title = "Hawaii", frame = FALSE, bg.color = NA, 
            title.position = c("left", "bottom"))
```

```{r}
alaska_map = tm_shape(alaska) +
  tm_polygons() + 
  tm_layout(title = "Alaska", frame = FALSE, bg.color = NA)
```

## Map arrangement

```{r}
grid.newpage()
pushViewport(viewport(layout = grid.layout(2, 1, heights = unit(c(us_states_alaska_ratio, 1), "null"))))
print(alaska_map, vp = viewport(layout.pos.row = 1))
print(us_states_map, vp = viewport(layout.pos.row = 2))
print(hawaii_map, vp = viewport(x = 0.25, y = 0.1,
                                height = us_states_hawaii_ratio))
```

