#!/bin/bash

# Source: https://github.com/textmining-infopros/chapter7/blob/master/binder/start

# This is to fix error ``GLIBCXX_3.4.26 not found from RStudio` when I try to load datefile package in RStudio.
# (Don't get the issue when is irkernel.) Solution based on 
# https://discourse.jupyter.org/t/glibcxx-3-4-26-not-found-from-rstudio/7778/8?u=fomightez
set -e
export LD_LIBRARY_PATH=${NB_PYTHON_PREFIX}/lib:${LD_LIBRARY_PATH}


# this must be last line according to 
# https://repo2docker.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"